document.getElementById("paginatitel").innerText = "Dit is de paginatitel";
document.getElementById("subkop").innerText = "Dit is de subkop";
document.getElementById("aap1").src = "img/little-monkey.jpg";
document.getElementById("aap2").src = "img/monkey.jpg";
document.getElementById("blokje1").style.backgroundColor = "blue";
document.getElementById("blokje1").style.textAlign = "center"
document.getElementById("blokje2").style.backgroundColor = "darkgreen";
document.getElementById("blokje2").style.textAlign = "center"
document.getElementById("blokje2").style.marginTop = "25px";
document.getElementById("blokje3").style.backgroundColor = "yellow";
document.getElementById("blokje3").style.marginTop = "50px";
document.getElementById("blokje3").style.textAlign = "right"
document.getElementById("blokje4").style.backgroundColor = "red";
document.getElementById("blokje4").style.textAlign = "left"